### ISSUE TITLE
helper package for simplex trees?

### ISSUE THREAD

**Issue by corybrunson** [peekxc/Mapper#1]
Thanks for the very nice implementation. So far as i can tell, the simplex tree functionality has not been implemented elsewhere for use in R, so i wonder if you've considered making it a separate, helper package that **Mapper** depends on? I'm sure i'm not the only person who'd make use of an efficient standalone package for simplicial complexes. This of course isn't a quick bug report or feature request, i'm just interested whether that's part of the medium-term plan for the package.

**Comment by peekxc** [comment]
Hi @corybrunson. I don't see why not.  I'll add porting the module to another package to do list, shouldn't be too much work.

Regarding the medium-term plan for e.g. the SimplexTree module, there still basic operations I need to finish implementing (locating cofaces efficiently, collapses, k-expansion, etc.). Those are what I'm doing next

**Comment by corybrunson** [comment]
Cool! I appreciate it, and i'll be keen to see how it shapes up.

**Comment by peekxc** [comment]
@corybrunson 

See https://github.com/peekxc/simplextree. 

Better docs, tests, etc. will have to come later when I find more time, but I think the little bit that's there should give you an idea on the planned trajectory of the package. 

Right now, there's very basic, needs-to-be-better-tested functionality for: 

- insertions and removals 
- elementary collapses
- edge contractions 
- arbitrary traversals (e.g. cofaces, links, etc., see `apply` function)
- basic serialization + deserialization 
- export to graph / list options

k-expansions for flag complexes along with other forms of collapses + traversals are planned next. I'm not immediately planning on doing things like the witness complex constructions. If you need something in particular just let me know.

**Comment by corybrunson** [comment]
@peekxc this is great. I'm trying out the functionality on small examples, and hopefully i'll be able to test the efficiency on larger data in time. Thank you for spinning out the helper package!

For the time being, if there are documentation suggestions or bugs i think i can resolve, would you prefer feedback in the form of issues or of pull requests? (I'll raise one issue momentarily.)

**Comment by peekxc** [comment]
I look forward to seeing the results and doing some benchmarking myself! 

Either PRs or issues, whichever you prefer!

**Comment by peekxc** [comment]
Closing this issue.
